# Generated by Django 3.1 on 2020-09-23 15:01

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_product_publish_date'),
        ('profiles', '0002_auto_20200903_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stripe_payment_id', models.CharField(default='', max_length=254)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('paid', 'Paid'), ('payment_failed', 'Payment Failed'), ('shipped', 'Shipped')], max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('gift_message', models.TextField(blank=True, default='', null=True)),
                ('payment_street_address1', models.CharField(max_length=80)),
                ('payment_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('payment_town_or_city', models.CharField(max_length=40)),
                ('payment_county', models.CharField(blank=True, max_length=80, null=True)),
                ('payment_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_country', django_countries.fields.CountryField(max_length=2)),
                ('shipping_full_name', models.CharField(max_length=50)),
                ('shipping_street_address1', models.CharField(max_length=80)),
                ('shipping_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_town_or_city', models.CharField(max_length=40)),
                ('shipping_county', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('shipping', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
