# Generated by Django 3.1 on 2020-09-09 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
        ('profiles', '0002_auto_20200903_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('publish_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fan_art', to='series.series')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_art', to='profiles.userprofile')),
            ],
        ),
    ]
