# Generated by Django 3.1 on 2020-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanart',
            name='artist_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
