# Generated by Django 3.1 on 2020-09-10 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200903_0907'),
        ('fan_art', '0002_fanart_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanart',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='fanart',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_art', to='profiles.userprofile'),
        ),
    ]
