# Generated by Django 3.1 on 2020-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('page_url', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
    ]
