# Generated by Django 3.1 on 2020-09-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=254)),
                ('product_type', models.CharField(choices=[('hard_back_book', 'Hard Back Book'), ('paper_back_book', 'Paper Back Book'), ('e_book', 'E-Book'), ('audio_book', 'Audio Book'), ('merchandise', 'Merchandise')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recommended_audience_age', models.IntegerField()),
                ('author', models.CharField(blank=True, max_length=254, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=254, null=True)),
                ('isbn', models.CharField(blank=True, max_length=254, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('run_time', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('narrator', models.CharField(blank=True, max_length=254, null=True)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='series.series')),
            ],
        ),
    ]
