# Generated by Django 3.1 on 2020-09-09 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200906_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
