# Generated by Django 3.1 on 2020-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'product_type']},
        ),
        migrations.AddField(
            model_name='product',
            name='list_in_shop',
            field=models.BooleanField(default=True),
        ),
    ]
